# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mqtt_version <- function() {
    .Call('_mqtt_mqtt_version', PACKAGE = 'mqtt')
}

mqtt_init <- function() {
    .Call('_mqtt_mqtt_init', PACKAGE = 'mqtt')
}

mqtt_free <- function() {
    .Call('_mqtt_mqtt_free', PACKAGE = 'mqtt')
}

subscribe_ <- function(host, port, keepalive, client_id, topic, qos, connection_cb, message_cb, disconnect_cb) {
    invisible(.Call('_mqtt_subscribe_', PACKAGE = 'mqtt', host, port, keepalive, client_id, topic, qos, connection_cb, message_cb, disconnect_cb))
}

