# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Get mosquitto library version
#'
mqtt_version <- function() {
    .Call('_mqtt_mqtt_version', PACKAGE = 'mqtt')
}

#' Get mosquitto library version
#'
mqtt_init <- function() {
    .Call('_mqtt_mqtt_init', PACKAGE = 'mqtt')
}

#' Free resources when done
#'
mqtt_free <- function() {
    .Call('_mqtt_mqtt_free', PACKAGE = 'mqtt')
}

subscribe <- function(host, port, keepalive, client_id, topic, qos, connection_cb, message_cb) {
    invisible(.Call('_mqtt_subscribe', PACKAGE = 'mqtt', host, port, keepalive, client_id, topic, qos, connection_cb, message_cb))
}

